### PR TITLE
Show CC info in the customer order detail page and the admin order detail page

### PR DESCRIPTION
**Pull request by johnmccombs1**
Show CC info in the customer order detail page and the admin order detail page
See the demo screenshots:
http://prntscr.com/sph9g1
http://prntscr.com/sphb6v

Fixes: https://boltpay.atlassian.net/browse/M1P-61

#changelog Show CC info in the customer order detail page and the admin order detail page

# Type of change

- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Test

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [x] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# Checklist:

- [x] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [x] I have added my Asana task link and provided a changelog message if applicable.

### CODE REVIEW

**Comment by mccottry** [comment]
@johnmccombs1 I have only one small question.
It seems like we have removed the indicator stating that this is a Bolt order from the Payment method section of the admin.  Is this correct?  If so, is this desired?

**Comment by johnmccombs1** [comment]
@mccottry No, I only refactored the code here to show the payment info via method _prepareSpecificInformation. The old solution uses the template to show the payment information. Below are the detail screenshots before and after my fix:
Admin order detail page
Before fix:
http://prntscr.com/srpmxc
After fix:
https://prnt.sc/sphb6v

Customer account page
Before fix:
http://prntscr.com/srppw4
After fix:
https://prnt.sc/sph9g1

**Comment by mccottry** [comment]
@johnmccombs1 
My eyes might be fooling me, but is there a left align problem?
image

**Comment by adentong** [comment]
@johnmccombs1 Do you think you could address @mccottry's question?

**Comment by johnmccombs1** [comment]
@mccottry  That is expected as the credit card information (credit card type and credit card number) is in a table element by core Magento. 
See here - http://prntscr.com/suf4px
Merging the PR

**Pull request merged**
