### PR TITLE
Add missing files

### PR DESCRIPTION
**Pull request by adentong**
Copy and pasted from Leon's commit.

#changelog Add missing files

# Type of change

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Test

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [x] Successfully tested locally (or docker image)
- [ ] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [ ] I have added my Asana task link and provided a changelog message if applicable.

### CODE REVIEW

**Comment by adentong** [comment]
@matt-thomason https://github.com/BoltApp/bolt-magento1/pull/724. In system.xml you can see the model is changed to boltpay/admin_apiKey, but there's no such file under Model/Admin.

**Comment by adentong** [comment]
And if we look at https://github.com/BoltApp/bolt-magento1/commit/b263e96709c07a9f8a15868e5921b06e3fc295a1 the added files are there. I think Leon accidentally left out those two files when he force pushed.

**Comment by adentong** [comment]
I only noticed cuz I was testing my admin config changes locally and the configuration page threw an exception and crashed.

**Comment by matt-thomason** [comment]
Thanks @adentong

**Pull request merged**
