### PR TITLE
Handles notice displayed about $transaction in developer mode for pending hooks

### PR DESCRIPTION
**Pull request by mccottry**
# Description
Handles notice displayed in developer mode for transactions.  This bug and fix does not affect production and is being applied for testing and dev environments.

Fixes: https://app.asana.com/0/941895179897714/1157028338214625

# Type of change

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Test

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [x] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] New and existing unit tests pass locally with my changes.
- [x] I have created or modified unit tests to sufficiently cover my changes.
- [x] I have added my Asana task link and provided a changelog message if applicable.

### CODE REVIEW

**Comment by adentong** [comment]
@mccottry Can you address Matt and Alex's concerns? Looks like this PR is almost in a good state.

**Comment by mccottry** [comment]
> Can you add a comment above line 75? This is reasonable in the context of this PR, but I think a future viewer could be confused as to why we expect a case where we set `$transaction` to be null.

@matt-thomason Done

**Comment by mccottry** [comment]
> Can you update or add corresponding test？

@Jiyuan-Bolt Done

**Comment by mccottry** [comment]
> @mccottry Can you address Matt and Alex's concerns? Looks like this PR is almost in a good state.

@adentong Done

**Pull request merged**
