### PR TITLE
Create order optimization with Benchmark Profiler

### PR DESCRIPTION
**Pull request by mccottry**
# Description
To reduce processing time for create_order, we eliminate recalculation of shipping, which has been done sufficiently via the shipping and tax end point.  We also add the ability to log execution times via a benchmarking so that we may quantify processing time.

Fixes: https://app.asana.com/0/inbox/544708310157128/1132981769648030/1132983838706810

# Type of change

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [x] Successfully tested locally (or docker image)
- [x] Successfully tested on a staging or sandbox server
- [x] Successfully tested on a merchant's staging server

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [ ] I have created or modified unit tests to sufficiently cover my changes.

### CODE REVIEW

**Comment by mccottry** [comment]
Benchmark Profiler Output for my staging server:
```
*****************************************************

-- Benchmark  1 --
*Bolt controller predispatch started*
Time since previous benchmark: *0.016s*
Time since benchmark profiling was started: 0.016s
Percent of total benchmarked processing time: *2.40%*

-- Benchmark  2 --
*Finished Bolt controller predispatch*
Time since previous benchmark: *0.005s*
Time since benchmark profiling was started: 0.021s
Percent of total benchmarked processing time: *0.76%*

-- Benchmark  3 --
*Starting create order controller endpoint*
Time since previous benchmark: *0.074s*
Time since benchmark profiling was started: 0.095s
Percent of total benchmarked processing time: *11.37%*

-- Benchmark  4 --
*Finished looking up order by quote id*
Time since previous benchmark: *0.008s*
Time since benchmark profiling was started: 0.103s
Percent of total benchmarked processing time: *1.23%*

-- Benchmark  5 --
*Calling createOrder function*
Time since previous benchmark: *0s*
Time since benchmark profiling was started: 0.103s
Percent of total benchmarked processing time: *0.02%*

-- Benchmark  6 --
*Potentially starting to fetch bolt transaction*
Time since previous benchmark: *0s*
Time since benchmark profiling was started: 0.103s
Percent of total benchmarked processing time: *0.01%*

-- Benchmark  7 --
*Finished fetching bolt transaction. Looking up quotes.*
Time since previous benchmark: *0s*
Time since benchmark profiling was started: 0.103s
Percent of total benchmarked processing time: *0.00%*

-- Benchmark  8 --
*Looked up quotes.*
Time since previous benchmark: *0.002s*
Time since benchmark profiling was started: 0.105s
Percent of total benchmarked processing time: *0.37%*

-- Benchmark  9 --
*Dispatching event bolt_boltpay_order_creation_before*
Time since previous benchmark: *0.057s*
Time since benchmark profiling was started: 0.163s
Percent of total benchmarked processing time: *8.79%*

-- Benchmark  10 --
*Dispatched event bolt_boltpay_order_creation_before*
Time since previous benchmark: *0s*
Time since benchmark profiling was started: 0.163s
Percent of total benchmarked processing time: *0.01%*

-- Benchmark  11 --
*Validated session data*
Time since previous benchmark: *0.081s*
Time since benchmark profiling was started: 0.244s
Percent of total benchmarked processing time: *12.49%*

-- Benchmark  12 --
*Saved customer information*
Time since previous benchmark: *0s*
Time since benchmark profiling was started: 0.244s
Percent of total benchmarked processing time: *0.01%*

-- Benchmark  13 --
*Saved address info*
Time since previous benchmark: *0.01s*
Time since benchmark profiling was started: 0.254s
Percent of total benchmarked processing time: *1.52%*

-- Benchmark  14 --
*Applying shipping*
Time since previous benchmark: *0s*
Time since benchmark profiling was started: 0.254s
Percent of total benchmarked processing time: *0.01%*

-- Benchmark  15 --
*Applying shipping - Applying shipping address data*
Time since previous benchmark: *0.001s*
Time since benchmark profiling was started: 0.255s
Percent of total benchmarked processing time: *0.12%*

-- Benchmark  16 --
*Finished applying shipping - Applying shipping address data*
Time since previous benchmark: *0.014s*
Time since benchmark profiling was started: 0.269s
Percent of total benchmarked processing time: *2.15%*

-- Benchmark  17 --
*Finished applying shipping*
Time since previous benchmark: *0.059s*
Time since benchmark profiling was started: 0.328s
Percent of total benchmarked processing time: *8.98%*

-- Benchmark  18 --
*Collecting totals to validate*
Time since previous benchmark: *0.015s*
Time since benchmark profiling was started: 0.342s
Percent of total benchmarked processing time: *2.25%*

-- Benchmark  19 --
*Finished collecting totals to validate*
Time since previous benchmark: *0.063s*
Time since benchmark profiling was started: 0.406s
Percent of total benchmarked processing time: *9.71%*

-- Benchmark  20 --
*Validated coupons*
Time since previous benchmark: *0.004s*
Time since benchmark profiling was started: 0.41s
Percent of total benchmarked processing time: *0.66%*

-- Benchmark  21 --
*Validated subTotals*
Time since previous benchmark: *0.002s*
Time since benchmark profiling was started: 0.412s
Percent of total benchmarked processing time: *0.32%*

-- Benchmark  22 --
*Searched for existing order*
Time since previous benchmark: *0.001s*
Time since benchmark profiling was started: 0.413s
Percent of total benchmarked processing time: *0.18%*

-- Benchmark  23 --
*Submitting order*
Time since previous benchmark: *0.001s*
Time since benchmark profiling was started: 0.414s
Percent of total benchmarked processing time: *0.18%*

-- Benchmark  24 --
*Submitted order and validated it*
Time since previous benchmark: *0.175s*
Time since benchmark profiling was started: 0.589s
Percent of total benchmarked processing time: *26.79%*

-- Benchmark  25 --
*Finished post order processing*
Time since previous benchmark: *0.06s*
Time since benchmark profiling was started: 0.649s
Percent of total benchmarked processing time: *9.17%*

-- Benchmark  26 --
*Running independent merchant third-party code via checkout_submit_all_after*
Time since previous benchmark: *0s*
Time since benchmark profiling was started: 0.649s
Percent of total benchmarked processing time: *0.01%*

-- Benchmark  27 --
*Finished running independent merchant third-party code via checkout_submit_all_after*
Time since previous benchmark: *0.001s*
Time since benchmark profiling was started: 0.65s
Percent of total benchmarked processing time: *0.20%*

-- Benchmark  28 --
*Dispatched bolt_boltpay_order_creation_after*
Time since previous benchmark: *0s*
Time since benchmark profiling was started: 0.65s
Percent of total benchmarked processing time: *0.02%*

-- Benchmark  29 --
*Completed createOrder function*
Time since previous benchmark: *0s*
Time since benchmark profiling was started: 0.651s
Percent of total benchmarked processing time: *0.01%*

-- Benchmark  30 --
*Response sent to Bolt*
Time since previous benchmark: *0.002s*
Time since benchmark profiling was started: 0.652s
Percent of total benchmarked processing time: *0.27%*

*****************************************************

-- Aggregate Benchmark Processing Time Summary --

26.79% - Benchmark 24  - Submitted order and validated it - *0.175s*
12.49% - Benchmark 11  - Validated session data - *0.081s*
11.37% - Benchmark 3   - Starting create order controller endpoint - *0.074s*
 9.71% - Benchmark 19  - Finished collecting totals to validate - *0.063s*
 9.17% - Benchmark 25  - Finished post order processing - *0.060s*
 8.98% - Benchmark 17  - Finished applying shipping - *0.059s*
 8.79% - Benchmark 9   - Dispatching event bolt_boltpay_order_creation_before - *0.057s*
 2.40% - Benchmark 1   - Bolt controller predispatch started - *0.016s*
 2.25% - Benchmark 18  - Collecting totals to validate - *0.015s*
 2.15% - Benchmark 16  - Finished applying shipping - Applying shipping address data - *0.014s*
 1.52% - Benchmark 13  - Saved address info - *0.010s*
 1.23% - Benchmark 4   - Finished looking up order by quote id - *0.008s*
 0.76% - Benchmark 2   - Finished Bolt controller predispatch - *0.005s*
 0.66% - Benchmark 20  - Validated coupons - *0.004s*
 0.37% - Benchmark 8   - Looked up quotes. - *0.002s*
 0.32% - Benchmark 21  - Validated subTotals - *0.002s*
 0.27% - Benchmark 30  - Response sent to Bolt - *0.002s*
 0.20% - Benchmark 27  - Finished running independent merchant third-party code via checkout_submit_all_after - *0.001s*
 0.18% - Benchmark 23  - Submitting order - *0.001s*
 0.18% - Benchmark 22  - Searched for existing order - *0.001s*
 0.12% - Benchmark 15  - Applying shipping - Applying shipping address data - *0.001s*
 0.02% - Benchmark 28  - Dispatched bolt_boltpay_order_creation_after - *0.000s*
 0.02% - Benchmark 5   - Calling createOrder function - *0.000s*
 0.01% - Benchmark 6   - Potentially starting to fetch bolt transaction - *0.000s*
 0.01% - Benchmark 29  - Completed createOrder function - *0.000s*
 0.01% - Benchmark 26  - Running independent merchant third-party code via checkout_submit_all_after - *0.000s*
 0.01% - Benchmark 10  - Dispatched event bolt_boltpay_order_creation_before - *0.000s*
 0.01% - Benchmark 14  - Applying shipping - *0.000s*
 0.01% - Benchmark 12  - Saved customer information - *0.000s*
 0.00% - Benchmark 7   - Finished fetching bolt transaction. Looking up quotes. - *0.000s*

Total Processing Time: *0.652s*

*****************************************************
```

**Comment by daisy1754** [comment]
> Successfully tested on a merchant's staging server
Do you mind sharing who's server is used and how was the result? given your sandbox serve is very fast (less than one second), I'm more curious how this works in more real-world like settings

**Comment by mccottry** [comment]
> > Successfully tested on a merchant's staging server
> 
> Do you mind sharing who's server is used and how was the result? given your sandbox serve is very fast (less than one second), I'm more curious how this works in more real-world like settings

@daisy1754 
I'll post you some staging server settings in the morning.  I've ran the numbers with an earlier version of this code, but want to redo them with this proposed codebase.

**Comment by mccottry** [comment]
> This is great @mccottry. It's possible that in the future we should explore separating this from `LoggerTrait` as it serves a slightly different purpose, but this looks good to get out for 2.0.1.

@matt-thomason 
Yep, I was thinking about that (and the logging solution that we currently have.)  2.0.2, I definitely have some proposals and have this separated.

**Pull request merged**
