### PR TITLE
Javascript filter event

### PR DESCRIPTION
**Pull request by mccottry**
https://app.asana.com/0/544708310157130/1108368077993436

Provides an easy means to make changes to the BoltCheckout default javascript. 
-----------------------------------------------------

**Simple example [Adding variables before BoltCheckout.configure for callback use, method call after]:** 

_in config.xml_
```
   ...
    <events>
      <bolt_boltpay_filter_bolt_checkout_javascript>
        <observers>
          <bolt_boltpay_prepend_variables_postfix_method_call>
            <class>Bolt_Custom_Model_Observer</class>
            <method>addCustomVariablesAndMethodsToJS</method>
          </bolt_boltpay_prepend_variables_postfix_method_call>
        </observers>
      </bolt_boltpay_filter_bolt_checkout_javascript>
   </events>
```

_in the Bolt_Custom_Model_Observer class_
```
    /**
     * Adds custom javascript to BoltCheckout javascript
     *
     * @param Varien_Event_Observer $observer  event contains wrapped value
     */
    public function addCustomVariablesAndMethodsToJS($observer)
    {
        /** @var Varien_Object $valueWrapper */
        $valueWrapper = $observer->getEvent()->getData('valueWrapper');
        $originalBoltCheckoutJs = $valueWrapper->getValue();
        $affiliateId = $this->getAffiliateIdFromSession();

        $amendedBoltCheckoutJs = "
             var affiliateId = '$affiliateId'; 
             $originalBoltCheckoutJs
             setAffiliateCookies();
        ";

        $valueWrapper->setValue($amendedBoltCheckoutJs);
    }

```

-----------------------------------------------------
**Advanced example - internal code manipulation** 

_in config.xml_
```
   ...
    <events>
      <bolt_boltpay_filter_bolt_checkout_javascript>
        <observers>
          <bolt_boltpay_internal_js_edits>
            <class>Bolt_Custom_Model_Observer</class>
            <method>modifyCheckMethod</method>
          </bolt_boltpay_prepend_variables_postfix_method_call>
        </observers>
      </bolt_boltpay_internal_js_edits>
   </events>
```

_in the Bolt_Custom_Model_Observer class_
```
    /**
     * Adds custom javascript to BoltCheckout javascript
     *
     * @param Varien_Event_Observer $observer  event contains wrapped value
     */
    public function modifyCheckMethod($observer)
    {
        /** @var Varien_Object $valueWrapper */
        $valueWrapper = $observer->getEvent()->getData('valueWrapper');
        $additionalParameters = $observer->getEvent()->getData('parameters');

        $originalBoltCheckoutJs = $valueWrapper->getValue();
        $quote = $additionalParameters['quote'];
        $checkoutType = $additionalParameters['checkoutType'];

        $originalCheckFunction = Mage::helper('boltpay')
           ->buildOnCheckCallback($checkoutType, $quote->isVirtual());
        $newCheckFunction = "
           sendConversionToGA();
          $originalCheckFunction
        " . ($this->getIsLoginRequired() && !$this->getIsLoggedIn()) ? "return false;" : "return true;";

        $updatedBoltCheckoutJs  = str_replace ( $originalCheckFunction  , $newCheckFunction , $originalBoltCheckoutJs );

        $valueWrapper->setValue($updatedBoltCheckoutJs);
    }
```

### CODE REVIEW

**Comment by mccottry** [comment]
> Just want to make sure we follow YAGNI principle here - "should not add functionality until deemed necessary" https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it
> 
> Do we have specific use case in mind?

Thanks for this article.  It is an interesting philosophy.  It is good to balance forward thinking with XP principles.

To answer your question directly, this PR was inspired by an onsite integration, so came as a result of a specific use case.  In this example, here we see an override of a core Bolt Plugin method `buildBoltCheckoutJavascript`:

```
class Bolt_Bolt_Block_Checkout_Boltpay extends Bolt_Boltpay_Block_Checkout_Boltpay
{
    const CONFIG_PATH_ALLOW_GUEST_CHECKOUT = 'checkout/options/guest_checkout';

    /**
     * Generate BoltCheckout Javascript for output.
     *
     * @param string $checkoutType  'multi-page' | 'one-page' | 'admin' | 'firecheckout'
     * @param $quote
     * @param $hintData
     * @param $cartData
     * @return string
     */
    public function buildBoltCheckoutJavascript($checkoutType, $quote, $hintData, $cartData)
    {
        /* @var Bolt_Boltpay_Helper_Api $boltHelper */
        $boltHelper = Mage::helper('boltpay');

        $jsonCart = (is_string($cartData)) ? $cartData : json_encode($cartData);
        $jsonHints = json_encode($hintData, JSON_FORCE_OBJECT);

        //////////////////////////////////////////////////////
        // Collect the event Javascripts
        // We execute these events as early as possible, typically
        // before Bolt defined event JS to give merchants the
        // opportunity to do full overrides
        //////////////////////////////////////////////////////
        $checkCustom = $boltHelper->getPaymentBoltpayConfig('check', $checkoutType);
        $onCheckoutStartCustom = $boltHelper->getPaymentBoltpayConfig('on_checkout_start', $checkoutType);
        $onShippingDetailsCompleteCustom = $boltHelper->getPaymentBoltpayConfig('on_shipping_details_complete', $checkoutType);
        $onShippingOptionsCompleteCustom = $boltHelper->getPaymentBoltpayConfig('on_shipping_options_complete', $checkoutType);
        $onPaymentSubmitCustom = $boltHelper->getPaymentBoltpayConfig('on_payment_submit', $checkoutType);
        $successCustom = $boltHelper->getPaymentBoltpayConfig('success', $checkoutType);
        $closeCustom = $boltHelper->getPaymentBoltpayConfig('close', $checkoutType);

        $onCheckCallback = $this->buildOnCheckCallback($checkoutType, $quote);
        $onSuccessCallback = $this->buildOnSuccessCallback($successCustom, $checkoutType);
        $onCloseCallback = $this->buildOnCloseCallback($closeCustom, $checkoutType);

        $requiredCheck = ($checkoutType === self::CHECKOUT_TYPE_FIRECHECKOUT)
            ? ""
            : "
                    if (!json_cart.orderToken) {
                        if (typeof BoltPopup !== \"undefined\") {
                            BoltPopup.addMessage(json_cart.error).show();
                        } else {
                            alert(json_cart.error);
                        }
                        return false;
                    }
            "
        ;

        return ("
            var json_cart = $jsonCart;
            var json_hints = $jsonHints;
            var quote_id = '{$quote->getId()}';
            var order_completed = false;

            window.BC = BoltCheckout.configure(
                json_cart,
                json_hints,
                {
                  check: function() {
                    $requiredCheck
                    $checkCustom
                    $onCheckCallback
                    ". ($this->isLoginRequired() ? "
                    window.setInitiateCheckoutCookie(); 
                    window.location.replace('{$this->getLoginUrl()}');" : "" )."
                    
                    return ". ($this->isBoltModalOpenable() ? "true" : "false")."; 
                  },
                  
                  onCheckoutStart: function() {
                    // This function is called after the checkout form is presented to the user.
                    $onCheckoutStartCustom
                  },
                  
                  onShippingDetailsComplete: function() {
                    // This function is called when the user proceeds to the shipping options page.
                    // This is applicable only to multi-step checkout.
                    $onShippingDetailsCompleteCustom
                    validateQuote('{$quote->getId()}');
                  },
                  
                  onShippingOptionsComplete: function() {
                    // This function is called when the user proceeds to the payment details page.
                    // This is applicable only to multi-step checkout.
                    $onShippingOptionsCompleteCustom
                  },
                  
                  onPaymentSubmit: function() {
                    // This function is called after the user clicks the pay button.
                    $onPaymentSubmitCustom
                  },
                  
                  success: $onSuccessCallback,

                  close: function() {
                     $onCloseCallback
                  }
                }
        );");
    }
```

The same method in production looks like this:

```
    /**
     * Generate BoltCheckout Javascript for output.
     *
     * @param string $checkoutType  'multi-page' | 'one-page' | 'admin' | 'firecheckout'
     * @param Mage_Sales_Model_Quote $quote
     * @param $hintData
     * @param $cartData
     * @return string
     */
    public function buildBoltCheckoutJavascript($checkoutType, $quote, $hintData, $cartData)
    {
        /* @var Bolt_Boltpay_Helper_Data $boltHelper */
        $boltHelper = Mage::helper('boltpay');

        $jsonCart = (is_string($cartData)) ? $cartData : json_encode($cartData);
        $jsonHints = json_encode($hintData, JSON_FORCE_OBJECT);

        $callbacks = $boltHelper->getBoltCallbacks($checkoutType, $quote->isVirtual());

        $hintsTransformFunction = $boltHelper->getExtraConfig('hintsTransform');

        return ("
            var \$hints_transform = $hintsTransformFunction;
            
            var json_cart = $jsonCart;
            var json_hints = \$hints_transform($jsonHints);
            var quote_id = '{$quote->getId()}';
            var order_completed = false;

            BoltCheckout.configure(
                json_cart,
                json_hints,
                $callbacks
        );");
    }
```
For whatever reason or reasons, the `$this->buildOn***` methods were refactored from this class to a helper and so upon update to a new plugin, this integration would be dead on arrival (DOA) or dead on update (DOU).  Obviously, we want to avoid this.

The customization is attempting to add some inline cookie setting and forced login logic.  Also, the code attempts to define a variable `BC` in the global context, but probably could/should just use `BoltCheckout`, but regardless, the thought process for changing our default JS structure is understood and we should allow support for it.

While it maybe true that most of this could have been handled in a different way by using additional templates to define server-side derived variables in separate <script> block and then making use of those variables via the admin javascript event entry points, (which is the way that this particular integration will be modified), the `BC` variable initialization or any code that needed to be injected in sequence or modified in an advanced way could not happen without this filter.

Finally, if we see our developers are urging to use a construct, then perhaps we take on the philosophy of make life simpler and support the obvious paths to achieving that end.  Filters is going to become a way of life in dealing with this use case as it already is in WooCommerce.

**Comment by mccottry** [comment]
@daisy1754 
> Just want to make sure we follow YAGNI principle here - "should not add functionality until deemed necessary" https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it
> 
> Do we have specific use case in mind?

> Just want to make sure we follow YAGNI principle here - "should not add functionality until deemed necessary" https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it
> 
> Do we have specific use case in mind?

Thanks for this article.  It is an interesting philosophy.  It is good to balance forward thinking with XP principles.

To answer your question directly, this PR was inspired by an onsite integration, so came as a result of a specific use case.  In this example, here we see an override of a core Bolt Plugin method `buildBoltCheckoutJavascript`:

```
class Bolt_Bolt_Block_Checkout_Boltpay extends Bolt_Boltpay_Block_Checkout_Boltpay
{
    const CONFIG_PATH_ALLOW_GUEST_CHECKOUT = 'checkout/options/guest_checkout';

    /**
     * Generate BoltCheckout Javascript for output.
     *
     * @param string $checkoutType  'multi-page' | 'one-page' | 'admin' | 'firecheckout'
     * @param $quote
     * @param $hintData
     * @param $cartData
     * @return string
     */
    public function buildBoltCheckoutJavascript($checkoutType, $quote, $hintData, $cartData)
    {
        /* @var Bolt_Boltpay_Helper_Api $boltHelper */
        $boltHelper = Mage::helper('boltpay');

        $jsonCart = (is_string($cartData)) ? $cartData : json_encode($cartData);
        $jsonHints = json_encode($hintData, JSON_FORCE_OBJECT);

        //////////////////////////////////////////////////////
        // Collect the event Javascripts
        // We execute these events as early as possible, typically
        // before Bolt defined event JS to give merchants the
        // opportunity to do full overrides
        //////////////////////////////////////////////////////
        $checkCustom = $boltHelper->getPaymentBoltpayConfig('check', $checkoutType);
        $onCheckoutStartCustom = $boltHelper->getPaymentBoltpayConfig('on_checkout_start', $checkoutType);
        $onShippingDetailsCompleteCustom = $boltHelper->getPaymentBoltpayConfig('on_shipping_details_complete', $checkoutType);
        $onShippingOptionsCompleteCustom = $boltHelper->getPaymentBoltpayConfig('on_shipping_options_complete', $checkoutType);
        $onPaymentSubmitCustom = $boltHelper->getPaymentBoltpayConfig('on_payment_submit', $checkoutType);
        $successCustom = $boltHelper->getPaymentBoltpayConfig('success', $checkoutType);
        $closeCustom = $boltHelper->getPaymentBoltpayConfig('close', $checkoutType);

        $onCheckCallback = $this->buildOnCheckCallback($checkoutType, $quote);
        $onSuccessCallback = $this->buildOnSuccessCallback($successCustom, $checkoutType);
        $onCloseCallback = $this->buildOnCloseCallback($closeCustom, $checkoutType);

        $requiredCheck = ($checkoutType === self::CHECKOUT_TYPE_FIRECHECKOUT)
            ? ""
            : "
                    if (!json_cart.orderToken) {
                        if (typeof BoltPopup !== \"undefined\") {
                            BoltPopup.addMessage(json_cart.error).show();
                        } else {
                            alert(json_cart.error);
                        }
                        return false;
                    }
            "
        ;

        return ("
            var json_cart = $jsonCart;
            var json_hints = $jsonHints;
            var quote_id = '{$quote->getId()}';
            var order_completed = false;

            window.BC = BoltCheckout.configure(
                json_cart,
                json_hints,
                {
                  check: function() {
                    $requiredCheck
                    $checkCustom
                    $onCheckCallback
                    ". ($this->isLoginRequired() ? "
                    window.setInitiateCheckoutCookie(); 
                    window.location.replace('{$this->getLoginUrl()}');" : "" )."
                    
                    return ". ($this->isBoltModalOpenable() ? "true" : "false")."; 
                  },
                  
                  onCheckoutStart: function() {
                    // This function is called after the checkout form is presented to the user.
                    $onCheckoutStartCustom
                  },
                  
                  onShippingDetailsComplete: function() {
                    // This function is called when the user proceeds to the shipping options page.
                    // This is applicable only to multi-step checkout.
                    $onShippingDetailsCompleteCustom
                    validateQuote('{$quote->getId()}');
                  },
                  
                  onShippingOptionsComplete: function() {
                    // This function is called when the user proceeds to the payment details page.
                    // This is applicable only to multi-step checkout.
                    $onShippingOptionsCompleteCustom
                  },
                  
                  onPaymentSubmit: function() {
                    // This function is called after the user clicks the pay button.
                    $onPaymentSubmitCustom
                  },
                  
                  success: $onSuccessCallback,

                  close: function() {
                     $onCloseCallback
                  }
                }
        );");
    }
```

The same method in production looks like this:

```
    /**
     * Generate BoltCheckout Javascript for output.
     *
     * @param string $checkoutType  'multi-page' | 'one-page' | 'admin' | 'firecheckout'
     * @param Mage_Sales_Model_Quote $quote
     * @param $hintData
     * @param $cartData
     * @return string
     */
    public function buildBoltCheckoutJavascript($checkoutType, $quote, $hintData, $cartData)
    {
        /* @var Bolt_Boltpay_Helper_Data $boltHelper */
        $boltHelper = Mage::helper('boltpay');

        $jsonCart = (is_string($cartData)) ? $cartData : json_encode($cartData);
        $jsonHints = json_encode($hintData, JSON_FORCE_OBJECT);

        $callbacks = $boltHelper->getBoltCallbacks($checkoutType, $quote->isVirtual());

        $hintsTransformFunction = $boltHelper->getExtraConfig('hintsTransform');

        return ("
            var \$hints_transform = $hintsTransformFunction;
            
            var json_cart = $jsonCart;
            var json_hints = \$hints_transform($jsonHints);
            var quote_id = '{$quote->getId()}';
            var order_completed = false;

            BoltCheckout.configure(
                json_cart,
                json_hints,
                $callbacks
        );");
    }
```
For whatever reason or reasons, the `$this->buildOn***` methods were refactored from this class to a helper and so upon update to a new plugin, this integration would be dead on arrival (DOA) or dead on update (DOU).  Obviously, we want to avoid this.

The customization is attempting to add some inline cookie setting and forced login logic.  Also, the code attempts to define a variable `BC` in the global context, but probably could/should just use `BoltCheckout`, but regardless, the thought process for changing our default JS structure is understood and we should allow support for it.

While it maybe true that most of this could have been handled in a different way by using additional templates to define server-side derived variables in separate <script> block and then making use of those variables via the admin javascript event entry points, (which is the way that this particular integration will be modified), the `BC` variable initialization or any code that needed to be injected in sequence or modified in an advanced way could not happen without this filter.

Finally, maybe we can consider the philosophy of if we see our developers are urging to use a construct, then perhaps let's make life simpler and support the obvious paths to achieving that end.  Your proposal for adding event based actions and filters is going to become a way of life in dealing with this use case and several others in Magento 1 and 2, as it already is in WooCommerce.

**Comment by daisy1754** [comment]
@mccottry can you also provide how you would write Observer for `bolt_boltpay_filter_bolt_checkout_javascript` in the specific example above? I'm still trying to understand why it's needed.

Idea behind using event is to decouple our plugin and customization. For that, we need clear contracts on events that we can keep forever. Passing quote as an argument is example I can agree on because quote will remain core object for our use.

Passing JavaScript code as a string is not. We've been changing this string for random reasons and we'll change this again. If we change this string in the future, future plugin again will have a issue. Even worth, compiler or IDE can't help here because it's just a string from type perspective.

**Comment by mccottry** [comment]
> @mccottry can you also provide how you would write Observer for `bolt_boltpay_filter_bolt_checkout_javascript` in the specific example above? I'm still trying to understand why it's needed.
> 
> Idea behind using event is to decouple our plugin and customization. For that, we need clear contracts on events that we can keep forever. Passing quote as an argument is example I can agree on because quote will remain core object for our use.
> 
> Passing JavaScript code as a string is not. We've been changing this string for random reasons and we'll change this again. If we change this string in the future, future plugin again will have a issue. Even worth, compiler or IDE can't help here because it's just a string from type perspective.

@daisy1754 
I can rewrite the example above so that it is clear and will have the actual use case that this is used in ready for you for your early tomorrow.

**Comment by mccottry** [comment]
> @daisy1754
> I can rewrite the example above so that it is clear and will have the actual use case that this is used in ready for you for your early tomorrow.

As a second thought, I want to make a second pull request and think a little more about the gains versus following the YAGNI mode of thinking.

https://github.com/BoltApp/bolt-magento1/pull/298

**Comment by mccottry** [comment]
@daisy1754  @danac-gs  @johnmccombs1  @matt-thomason 
The examples have been updated.

**Pull request merged**
