### PR TITLE
Fix wiping out of order data in admin orders

### PR DESCRIPTION
**Pull request by mccottry**
# Description
A previous commit, in an attempt to refactor introduced a bug in the code that wipes out all order data with the exception of shipping method.  The presumed refactor's motivation was to attempt to not use the `$_POST` variable directly due to a Codacy ruleset complaint.

This PR fixes the code which directly causes the problem while respecting the initial motivation of using the Magento methods in preference to direct $_POST access.

Fixes: https://app.asana.com/0/941895179897714/1155073232509353

#changelog Bugfix for wiping out of order data in admin orders

# Type of change

- [x] Bug fix (change which fixes an issue)
- [ ] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Test

# How Has This Been Tested?
Please validate that you have tested your change in at least one of the following areas:

- [ ] Successfully tested locally (or docker image)
- [x] Successfully tested on a staging or sandbox server
- [ ] Successfully tested on a merchant's staging server

# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have created or modified unit tests to sufficiently cover my changes.
- [x] I have added my Asana task link and provided a changelog message if applicable.

### CODE REVIEW

**Comment by adentong** [comment]
@mccottry What's the status on this PR? I noticed that you opened the PR a month ago, but there has been no progress since.

**Comment by mccottry** [comment]
> @mccottry What's the status on this PR? I noticed that you opened the PR a month ago, but there has been no progress since.

@adentong I haven't taken the time to write the unit tests for this.  I will handle that shortly.

**Comment by mccottry** [comment]
Applying unit test to complete PR

**Comment by mccottry** [comment]
@adentong It doesn't seem the Peril checks run with each commit.  Perhaps it is only running on the first commit.

**Comment by adentong** [comment]
@mccottry  It's because when this PR was opened the PR template was \#changelog, but the rule checks for #changelog. The PR template has already been updated to be without the \.

**Pull request merged**
